f0rmiga/gcc-toolchain

toolchain/config.bzl.tpl
This is particularly important for static analysis tools that will treat `-isystem` differently than `-I` values.
=> fix: use -isystem instead of -I

toolchain/toolchain.BUILD.bazel.tpl
This allows individual binaries to be called with e.g. `bazel run @gcc_toolchain//:bin/m4`.
=> feat: expose all binaries

WORKSPACE, toolchain/config.bzl.tpl, toolchain/defs.bzl
By default, we set the rpath and dynamic linker to the ones in the sysroot. We still expose the option to disable this.
Setting the rpath is useful for using the exact shared objects we linked against, e.g. while `bazel test`ing. Also, on systems that have old glibc, it works without requiring the host to upgrade it. This works in tandem with setting the dynamic linker too.
For more details on how the dynamic linker works, see the man page for `ld.so`.
=> feat: set -rpath and --dynamic-linker to sysroot

WORKSPACE, toolchain/defs.bzl
I think users want to explicitly opt-in to this. Doing it by default produces non-portable ELF binaries.
=> fix: change defaults for hardcode_sysroot_{ld_linux,rpath}

toolchain/config.bzl.tpl
This is particularly useful when compiling only C code that doesn't rely on the C++ standard libraries since those symbols can be easily stripped out of the binary.
For C++ code, each binary will carry the necessary libstdc++ symbols, but I see this as an advantage since it makes the code more portable. Different than statically linking the libc, static linking of libstdc++ generally doesn't incur any penalties other than the output binary size, which is less than 1Mb in overhead.
=> feat: static libstdc++

WORKSPACE, toolchain/cc_toolchain_config.bzl
Both `-lstdc++` and `-lm` should be provided by the user. While they are
almost always used, it should be the decision of the user to provide
them. E.g. the user could provide `-l:libstdc++.a` instead of
`-lstdc++`.
=> fix: remove hardcoded ldflags

.bazelrc, WORKSPACE, internal.bzl, sysroot/flags.bzl, toolchain/defs.bzl, toolchain/toolchain.BUILD.bazel.tpl
This is a pre-requisite to allow this repository to work with Remote Build Execution.
With RBE, the environment is much more strict, so in this commit, I fix the missing GNU assembler as a dependency to the compilation files (previously working as a side-effect of it being in the local disk) and set the `-B` flags to the compiler so that it finds binutils in the right location.
=> feat: work with RBE

WORKSPACE, examples/openssl/BUILD.bazel, internal.bzl
This is making RBE confused when the host is macOS. rules_perl is not really doing anything useful for a hermetic toolchain anyways.
=> rm: rules_perl

WORKSPACE, toolchain/cc_toolchain_config.bzl
The `user_compile_flags_feature` was missing other compile actions, e.g., compiling C. This raised issues like missing extra `copts` from `cc_library` compiling `.c` code, leading to missing `-Wno-implicit-function-declaration` for the embedded `@zlib//:zlib`, which was producing spam warnings.
=> fix: user_compile_flags for all compile actions

platforms/BUILD.bazel
We not only switch to the official Python image but also pin it to a specific version (including its sha256).
=> fix: use a well-maintained image for rbe

docs/README.md, docs/defs.md, examples/hello_world_c/BUILD.bazel, toolchain/cc_toolchain_config.bzl, toolchain/defs.bzl
This translates better the intention of the feature as there are other cases we may want to tweak this feature even when compiling C++. E.g. when linking against another libstdc++.so the user may want.
=> rename: pure_c -> no_libstdcxx

WORKSPACE, docs/defs.md, toolchain/defs.bzl, toolchain/toolchain.BUILD.bazel.tpl
This matches the expectation of most users that the repository name is namespaced with `aspect` as prefix.
=> rename: workspace

sysroot/Dockerfile
This enables `-static-libgfortran` once we support Fortran.
=> fix: --enable-default-pie for gcc libs in sysroot

rules_fortran/defs.bzl
- Fixes the wrong linker flags in current_fortran_toolchain.
- Fixes the missing static archives from cc_import.
=> fix: rules_fortran

toolchain/defs.bzl
=> fix: exclude sysroot and some libs from bootlin

toolchain/defs.bzl
We were including the symlinks but not the real files. It can cause
problems on strict environments (e.g. RBE). Adding the glob:
```
"bin/{binary_prefix}-buildroot-*-" + bin
```
captures the real files.
I noticed on RBE that `collect2` would miss the hermetic `ld`.
=> fix: missing real files

examples/lapack/BUILD.bazel, internal.bzl
This example uses rules_foreign_cc to build LAPACK, which is a Fortran library.
=> feat: add lapack example

toolchain/defs.bzl
When passing different workspaces to customize the target compatibility, Label removes the workspace name, rendering the wrong string back into the BUILD.bazel files.
=> fix: target_compatible_with other workspaces

rules_fortran/defs.bzl, toolchain/cc_toolchain_config.bzl
This enables Fortran code (or dependent systems that use Fortran code) to be sanitized.
=> fix: sanitizers with Fortran

.github/workflows/new_issue.yaml, .github/workflows/new_pr.yaml
Rolling this out to all our OSS bazel rules repos to automatically tag new issues as `untriaged` and add new issues & PRs to the Aspect OSS Bazel Rules project
=> chore: add workflows for new issues & PRs

.pre-commit-config.yaml, renovate.json
No need to run CI on this one. Just lining renovate configs through our OSS repos. This repo was also missing our standard pre-commit hook.
=> chore: update renovate config and add pre-commit config

examples/avl/BUILD.bazel, examples/hello_world_c/BUILD.bazel, examples/hello_world_cpp/BUILD.bazel, examples/hello_world_fortran/BUILD.bazel, examples/openssl/BUILD.bazel, examples/protobuf/BUILD.bazel, examples/tabulate_fortran/BUILD.bazel
Sanity check that examples build incase `--build_tests_only` ever gets set by accident.
=> chore: add build_test targets to examples

rules_fortran/defs.bzl
I noticed that building some Fortran libraries would fail for not containing the include paths of transitive dependencies. This fixes it.
=> feat: add include paths of transitive deps for Fortran rules

sysroot/configure.sh
This was affecting mainly the static Fortran linking, which required -fpic or -fPIC to work.
=> fix: sysroot build libraries with position independent code

rules_fortran/defs.bzl
When a target is provided to the srcs attribute of the Fortran rules, it will now reuse precompiled objects, if available.
=> feat: reuse precompiled objects of targets in srcs

platforms/BUILD.bazel
The new image supports how the new toolchain binaries are built, more specifically to the ELF formats. The old image had incompatibilities with running the LTO plugin, throwing obscure errors regarding misalignment.
=> fix: bump rbe container image

docs/defs.md, toolchain/cc_toolchain_config.bzl, toolchain/defs.bzl
This fix allows RBE to work and have shared cache between systems as no absolute path cripples in, making all paths in flags deterministic.
A negative side-effect of this fix is that toolchains for all platforms that are registered will first extract the toolchain files, even for platforms that are not requested during build.
This negative impact is partially mitigated by PR #186 that significantly reduces the toolchain archive sizes to about 25% of the original size.
=> fix: use relative paths for includes and flags

toolchain/defs.bzl
As of Bazel 8, `--incompatible_disallow_empty_globs` has been turned on by default, so some of the globs in the toolchain don't work. This change keeps the same functionality, acting as if the flag was on.
=> fix: Allow empty globs for Bazel 8 compatibility

docs/defs.md, toolchain/cc_toolchain_config.bzl, toolchain/defs.bzl
If found a problem: Some assembly files depend on builtin imports (e.g. the ones in boringssl). Currently, the way we make those imports available to targets is by adding all the `-isystem` et.al. flags into `extra_xxxx` attributes and passing them down to the cc_toolchain_config. However, the cc_toolchain_config doesn't apply those flags to `ACTION_NAME.preprocessor_assemble`.
This PR adds an `extra_asmflags` attribute to `gcc_toolchain` (and all the way down the chain). This solves the issue because we populate that attribute with the same imports we use for C code, but it also allows consumers to specify flags for the assembler.
An alternative could be to apply `extra_cflags` to `ACTION_NAME.preprocessor_assemble`. This is also a good alternative, I don't have a strong opinion on the …
=> feat: Add extra_asmflags to pass custom flags to `ACTION_NAME.preprocessor_assemble`
